<?php

namespace common\models\ebay;

use yii\base\Model;

class DataPage extends Model
{

    public $items;
    public $itemCount;
    public $count;
    public $page;
    public $size;
    public $facets;

    public function rules()
    {
        return [
            ['items', 'string'],
            [['itemCount', 'count', 'page', 'size'], 'integer'],
        ];
    }

    public function __construct($config = [])
    {
        parent::__construct($config); // TODO: Change the autogenerated stub
        $this->items = [];
        $this->facets = [];
        $this->itemCount = 0;
        $this->count = 0;
        $this->page = 1;
        $this->size = 50;
    }


}
